#!/usr/bin/env node
// GENERATE apps/ops-console/src/icons.ts from the canon icon set copied into
// assets/icons/ (byte-faithful to platform-contracts@ba6f16d / canon v0.9.6;
// the 29-icon set is byte-identical across v0.9.1→v0.9.6 — the icons did not move).
// The names and bytes are canon's; icons.test.ts proves each embedded glyph's
// sha256 equals assets/icons/icons.manifest.json. Re-run after any icon bump:
//   pnpm --filter @platform/ops-console gen:icons
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const appDir = join(here, '..');
const iconsDir = join(appDir, 'assets', 'icons');
const manifest = JSON.parse(readFileSync(join(iconsDir, 'icons.manifest.json'), 'utf8'));
const names = Object.keys(manifest.icons).sort();

const entries = names
  .map((name) => {
    const svg = readFileSync(join(iconsDir, `${name}.svg`), 'utf8');
    return `  ${JSON.stringify(name)}: ${JSON.stringify(svg)},`;
  })
  .join('\n');

const out = `// GENERATED by scripts/gen-icons.mjs from assets/icons/ — DO NOT EDIT BY HAND.
// The 29 Grand Teint glyphs (canon v0.9.6, pin ba6f16d) as inline SVG strings
// (zero deps). Each is byte-verbatim from canon; icons.test.ts proves sha256
// fidelity to assets/icons/icons.manifest.json. currentColor is driven by the
// element's CSS \`color\`; size is set in CSS (the SVGs are viewBox-only).

export const OPS_ICON_NAMES = ${JSON.stringify(names)} as const;

export type OpsIconName = (typeof OPS_ICON_NAMES)[number];

export const opsIcon: Readonly<Record<OpsIconName, string>> = {
${entries}
};
`;

writeFileSync(join(appDir, 'src', 'icons.ts'), out);
console.log(`gen-icons: wrote src/icons.ts with ${names.length} glyphs`);
